# Generated by Django 4.0 on 2024-01-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashapura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
