# Generated by Django 4.0 on 2024-01-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashapura', '0004_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
