# Generated by Django 4.0 on 2024-01-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashapura', '0005_remove_user_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
