# Generated by Django 4.0 on 2024-01-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashapura', '0007_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetails',
            name='updated_at',
        ),
    ]
