# Generated by Django 4.0 on 2024-01-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashapura', '0008_remove_vehicledetails_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicledetails',
        ),
    ]
